public class Animation {
    public static String[] FramesOpening = {" @                                             \n/|\\\n/ \\ ",
                                            " @                                             \n/|\\\n/ \\ ",
                                            " @                                             \n/|\\\n/ \\ ",
                                            " @                                             \n/|\\\n/ \\ ",
                                            " @__ Hello !                                   \n/| \n/ \\",
                                            " @/  Hello !                                   \n/| \n/ \\",
                                            " @__ Hello !                                   \n/| \n/ \\",
                                            " @/  Hello !                                   \n/| \n/ \\",
                                            " @__ Hello !                                   \n/| \n/ \\",
                                            " @/  Hello !                                   \n/| \n/ \\",
                                            " @__ Hello !                                   \n/| \n/ \\",
                                            " @/  Hello !                                   \n/| \n/ \\",
                                            " @__ Hello !                                   \n/| \n/ \\",
                                            " @   Welcome to the Daily Task Manager (DTM)   \n<|>\n/ \\",
                                            " @   Welcome to the Daily Task Manager (DTM)   \n<|>\n/ \\",
                                            " @   Welcome to the Daily Task Manager (DTM)   \n<|>\n/ \\",
                                            " @__ Welcome to the Daily Task Manager (DTM)   \n<| \n/ \\",
                                            " @__ Welcome to the Daily Task Manager (DTM)   \n<| \n/ \\",
                                            " @__ Welcome to the Daily Task Manager (DTM)   \n<| \n/ \\",
                                            " @   Welcome to the Daily Task Manager (DTM)   \n<|>\n/ \\",
                                            " @   Welcome to the Daily Task Manager (DTM)   \n<|>\n/ \\",};

    public static String[] FramesClosing = {" @                                             \n/|\\\n/ \\ ",
                                            " @                                             \n/|\\\n/ \\ ",
                                            " @                                             \n/|\\\n/ \\ ",
                                            " @                                             \n/|\\\n/ \\ ",
                                            " @__ Good Bye !                                \n/| \n/ \\",
                                            " @/  Good Bye !                                \n/| \n/ \\",
                                            " @__ Good Bye !                                \n/| \n/ \\",
                                            " @/  Good Bye !                                \n/| \n/ \\",
                                            " @__ Good Bye !                                \n/| \n/ \\",
                                            " @/  Good Bye !                                \n/| \n/ \\",
                                            " @__ Good Bye !                                \n/| \n/ \\",
                                            " @/  Good Bye !                                \n/| \n/ \\",
                                            " @__ Good Bye !                                \n/| \n/ \\",
                                            " @   Have a Nice Day !                         \n<|>\n/ \\",
                                            " @   Have a Nice Day !                         \n<|>\n/ \\",
                                            " @   Have a Nice Day !                         \n<|>\n/ \\",
                                            " @__ Have a Nice Day !                         \n<| \n/ \\",
                                            " @__ Have a Nice Day !                         \n<| \n/ \\",
                                            " @__ Have a Nice Day !                         \n<| \n/ \\",
                                            " @   Have a Nice Day !                         \n<|>\n/ \\",
                                            " @   Have a Nice Day !                         \n<|>\n/ \\",};
}